### ISSUE TITLE
Feature Request: Hide page title if Hero block positioned first

### ISSUE THREAD

**Issue by seb86** [thatplugincompany/coblocks-theme#16]
It would be cool to have the page title hidden automatically if the Hero block is placed first on the page or just an option to hide the page title if the Hero block is added first.

The page title must still be visible for search engines so just make it go off screen for presentation purposes.

What do you think?

**Comment by seb86** [comment]
This CSS should do nicely for this option.

```css
.site-content {
    padding-top: 0;
}

.entry-header {
    text-indent: -9999px;
    height: 0;
    padding: 0;
    margin: 0;
}
```
